# Generated by Django 6.0.5 on 2026-05-20 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businesselement",
            old_name="name",
            new_name="type",
        ),
        migrations.AlterField(
            model_name="businesselement",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("11a75a47-84b3-4ca2-94b6-a6f5a5a0c699"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.businesselement",
                    ),
                ),
            ],
        ),
    ]
