# Generated by Django 6.0.5 on 2026-05-20 17:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_name_businesselement_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselement",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("47fd77ee-0c98-4c1c-86fe-72d2ca1d997a"),
                editable=False,
                unique=True,
            ),
        ),
    ]
