# Generated by Django 6.0.5 on 2026-05-20 18:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_businesselement_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="businesselement",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(default=False, max_length=100)),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.businesselement",
                    ),
                ),
            ],
        ),
    ]
