# Generated by Django 6.0.5 on 2026-05-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_order_description_alter_businesselement_code_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
