# Generated by Django 6.0.5 on 2026-05-20 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_products_product"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="creator",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="creator",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="auth.group",
            ),
        ),
    ]
