# Generated by Django 6.0.5 on 2026-05-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_order_creator_alter_product_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
