# Generated by Django 6.0.5 on 2026-05-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_order_description_remove_order_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="element",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.businesselement",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.order"
            ),
        ),
    ]
