services:

  postgres:
    image: postgres
    shm_size: "1gb"
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf:rw
      - postgresql:/var/lib/postgresql:rw
    networks:
      education:
        ipv4_address: ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}

  django:
    container_name: django
    build: .
    entrypoint: [ "./entrypoint.sh" ]
    command: [ "python3", "manage.py", "runserver", "0.0.0.0:${DJ_PORT}" ]
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJ_ADMIN_USER=${DJ_ADMIN_USER}
      - DJ_ADMIN_EMAIL=${DJ_ADMIN_EMAIL}
      - DJ_ADMIN_PASSWORD=${DJ_ADMIN_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      education:
        ipv4_address: ${DJ_HOST}
    ports:
      - ${DJ_PORT}:${DJ_PORT}
    depends_on:
      - postgres

volumes:
  postgresql:

networks:
  education:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
          gateway: 172.50.0.1
